# Generated by Django 6.1 on 2026-08-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='calc_debt',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Расчёт: сумма кредитов'),
        ),
        migrations.AddField(
            model_name='lead',
            name='calc_income',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Расчёт: официальный доход'),
        ),
        migrations.AddField(
            model_name='lead',
            name='calc_payments',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Расчёт: платежи в месяц'),
        ),
        migrations.AddField(
            model_name='lead',
            name='calc_result',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Расчёт: новый платёж'),
        ),
    ]
